# Generated by Django 6.0.1 on 2026-05-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0003_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('seminar', 'Seminar'), ('workshop', 'Workshop'), ('conference', 'Conference'), ('orientation', 'Orientation'), ('exam', 'Exam'), ('meeting', 'Meeting'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
